name: syrah_core
description: Core models and business logic for Syrah
version: 1.0.0
homepage: https://github.com/benyaminsalimi/syrah_app

environment:
  sdk: ^3.2.0

dependencies:
  # Models & Serialization
  freezed_annotation: ^2.4.0
  json_annotation: ^4.8.0

  # Database
  isar: ^3.1.0

  # Utils
  uuid: ^4.2.0
  collection: ^1.18.0
  archive: ^4.0.0
  crypto: ^3.0.3

dev_dependencies:
  test: ^1.24.0
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0
  isar_generator: ^3.1.0
  mocktail: ^1.0.0
  lints: ^5.0.0
